### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by SisyphusIsntHappy** [6fe9d454/bdsmlr-scripts#3]
```
python bdsmlr_get_blog_fast.py  [redacted] -u [redacted]  -p [redacted]
[redacted] No tags set, grabbing all posts
[redacted] Logged in ...
Traceback (most recent call last):
  File "/home/jon/bdsmlr-scripts/bdsmlr_get_blog_fast.py", line 202, in <module>
    main(args)
  File "/home/jon/bdsmlr-scripts/bdsmlr_get_blog_fast.py", line 99, in main
    true_end_page = list(map(int, filter(str.isnumeric, page_numbers)))[-1]
IndexError: list index out of range
```

What is happening here???

**Comment by 6fe9d454** [comment]
See #2, you may have the same problem. I've made a note in the readme about it, but in your profile's preferences you need to turn off infinite scrolling on archive pages for it to function. If you don't, it cannot find the page numbers (because they don't exist for infinite scrolling).

**Comment by 6fe9d454** [comment]
For reference, it is this option you need to enable (which disables infinite scrolling, bit backwards). 
![image](https://user-images.githubusercontent.com/92829505/169866764-fb497e31-5b21-4316-9a3c-d6e2d6703318.png)

**Comment by veneamin** [comment]
disabled inf scroll,  see total page count in browser, but still get error

**Comment by jebediah2** [comment]
Same here after disabling infinite scroll on both archives and others.

**Comment by adhuei** [comment]
Same situation here. The error still occurs even after disabling the infinite scroll. Is there anything we can do to fix this problem?
